Repository aeag/MenuFromProject-Qgis-Plugin, pull requests merged in 2024-11, with the labels that each got.

#109 add(tooling): PR autolabeler
  .github/labeler.yml
  .github/workflows/auto-labeler.yml
Labels: ci-cd, tooling

#121 refacto(quality): apply git hooks to existing codebase
  docs/conf.py
  menu_from_project/datamodel/project.py
  menu_from_project/datamodel/project_config.py
  menu_from_project/logic/cache_manager.py
  menu_from_project/logic/layer_load.py
  menu_from_project/logic/project_read.py
  menu_from_project/logic/qgs_manager.py
  menu_from_project/menu_from_project.py
  menu_from_project/toolbelt/preferences.py
  menu_from_project/ui/menu_conf_dlg.py
  tests/qgis/test_project_read.py
Labels: enhancement

#119 add(tooling): use issue form templates to gather feedback
  .github/ISSUE_TEMPLATE/10_bug_report.yml
  .github/ISSUE_TEMPLATE/15_feature_request.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: tooling

#112 fix(tooling): fix path for flake8
  .pre-commit-config.yaml
Labels: tooling

#113 update(docs): add contributing guidelines
  CHANGELOG.md
  CONTRIBUTING.md
  docs/development/contribute.md
Labels: UI, Documentation

#114 update(docs): complete contribute section
  docs/development.md
  docs/development/development.md
  docs/development/documentation.md
  docs/development/packaging.md
  docs/development/translation.md
  docs/index.md
  docs/misc/history.md
Labels: Documentation

#115 Packaging: modernize plugin package and release workflow
  .github/release.yml
  .github/workflows/documentation.yml
  .github/workflows/package_and_release.yml
  .github/workflows/packager.yml
  .github/workflows/release.yml
  LICENSE
  menu_from_project/i18n/plugin_translation.pro
Labels: ci-cd, packaging

#118 Fix: help menu was leading to a 404
  menu_from_project/doc/index-en.html
  menu_from_project/doc/index-fr.html
  menu_from_project/menu_from_project.py
  menu_from_project/metadata.txt
Labels: bug, UI

#120 update(packaging): set minimum version to 3.28
  menu_from_project/metadata.txt
Labels: packaging

#111 (feat): use profile cache dir
  menu_from_project/datamodel/project.py
  menu_from_project/logic/cache_manager.py
  menu_from_project/logic/custom_datatypes.py
  menu_from_project/toolbelt/preferences.py
  menu_from_project/ui/conf_dialog.ui
  menu_from_project/ui/menu_conf_dlg.py
  tests/qgis/test_project_read.py
Labels: enhancement, UI

#123 fix(ci): root's requirements file is required by setup-python
  .github/workflows/package_and_release.yml
  menu_from_project/resources/i18n/fr.qm
  menu_from_project/resources/i18n/fr.ts
  menu_from_project/resources/i18n/ja.qm
  menu_from_project/resources/i18n/ja.ts
  menu_from_project/resources/i18n/plugin_translation.pro
  requirements.txt
  requirements/packaging.txt
Labels: bug, dependencies, ci-cd

#126 fix(project read): must check if layer is available in qgs project
  menu_from_project/logic/layer_load.py
  menu_from_project/logic/project_read.py
  menu_from_project/logic/qgs_manager.py
  menu_from_project/logic/xml_utils.py
  menu_from_project/menu_from_project.py
Labels: bug
