Repository aeag/MenuFromProject-Qgis-Plugin, pull requests merged in 2024-12, with the labels that each got.

#139 fix(conf): need to remove projects setting before write
  menu_from_project/toolbelt/preferences.py
Labels: bug

#142 fix(settings): invalid remove use we must indicate projects
  menu_from_project/toolbelt/preferences.py
Labels: bug

#143 Fix/qgis 3 28 use
  menu_from_project/logic/cache_manager.py
Labels: bug

#146 Bring Qt6 compatibility
  menu_from_project/logic/cache_manager.py
  menu_from_project/logic/layer_load.py
  menu_from_project/logic/qgs_manager.py
  menu_from_project/menu_from_project.py
  menu_from_project/metadata.txt
  menu_from_project/ui/menu_conf_dlg.py
Labels: enhancement

#144 Docs: add how LMFP behaves during QGIS startup
  docs/conf.py
  docs/development/setup.md
  docs/how_does_it_works.md
  docs/index.md
  requirements/documentation.txt
Labels: dependencies, Documentation

#129 Feature: add location option to create menus in QGIS browser from project
  menu_from_project/logic/layer_load.py
  menu_from_project/menu_from_project.py
  menu_from_project/toolbelt/preferences.py
  menu_from_project/ui/menu_conf_dlg.py
  menu_from_project/ui/menu_layer_data_item_provider.py
Labels: enhancement

#152 feat(doc): add browser support
  docs/usage/en_use.md
  docs/usage/fr_use.md
Labels: Documentation

#154 fix(browser): don't add group that start with -
  docs/usage/en_use.md
  docs/usage/fr_use.md
  menu_from_project/ui/menu_layer_data_item_provider.py
Labels: bug, Documentation

#155 fix(browser): show load all action if children not created
  menu_from_project/ui/menu_layer_data_item_provider.py
Labels: bug
