Repository aeag/MenuFromProject-Qgis-Plugin, pull requests merged in 2025-01, with the labels that each got.

#156 update(docs): add QDT helper
  docs/index.md
  docs/usage/with_qdt.md
Labels: Documentation

#159 Feat/layer version and format
  menu_from_project/datamodel/project_config.py
  menu_from_project/logic/layer_load.py
  menu_from_project/logic/project_read.py
  menu_from_project/menu_from_project.py
  menu_from_project/ui/menu_layer_data_item_provider.py
  tests/projets/test-versions.qgz
  tests/qgis/test_project_read.py
Labels: enhancement

#133 Feat/refactor project configuration widget
  menu_from_project/datamodel/project.py
  menu_from_project/logic/custom_datatypes.py
  menu_from_project/menu_from_project.py
  menu_from_project/toolbelt/preferences.py
  menu_from_project/ui/conf_dialog.ui
  menu_from_project/ui/menu_conf_dlg.py
  menu_from_project/ui/menu_layer_data_item_provider.py
  menu_from_project/ui/project_list_model.py
  menu_from_project/ui/project_widget.py
  menu_from_project/ui/project_widget.ui
Labels: UI

#161 feat(projet conf): update merge selection
  menu_from_project/ui/project_widget.py
  menu_from_project/ui/project_widget.ui
Labels: UI

#162 feat(menu): always use version for layer action creation
  menu_from_project/menu_from_project.py
  menu_from_project/ui/menu_layer_data_item_provider.py
Labels: UI

#163 (fix): small fixes for project configuration UI
  menu_from_project/logic/cache_manager.py
  menu_from_project/logic/layer_load.py
  menu_from_project/logic/qgs_manager.py
  menu_from_project/menu_from_project.py
  menu_from_project/toolbelt/preferences.py
  menu_from_project/ui/menu_conf_dlg.py
  menu_from_project/ui/project_list_model.py
  menu_from_project/ui/project_widget.py
Labels: bug, UI

#160 add(docs): broadcast project's sponsors
  docs/conf.py
  docs/development/testing.md
  docs/index.md
  docs/misc/funding.md
  docs/static/logo_ae-disun.svg
  docs/static/logo_aeag.webp
  docs/static/logo_anfsi.webp
  docs/static/logo_charente_eaux.png
  docs/static/logo_etablissement_public_loire.png
  docs/static/logo_oslandia.png
  docs/static/logo_qdt.png
  docs/usage/en/configuration.md
  docs/usage/en/with_qdt.md
  docs/usage/fr/index.md
  docs/usage/fr/with_qdt.md
  docs/usage/how_does_it_works.md
  requirements/documentation.txt
Labels: dependencies, UI, Documentation
