Repository aeag/MenuFromProject-Qgis-Plugin, pull requests merged in 2025-03, with the labels that each got.

#177 Fix: Qt6 compatibility before releasing 2.4.0
  menu_from_project/menu_from_project.py
  menu_from_project/ui/dlg_settings.py
  menu_from_project/ui/project_list_model.py
  menu_from_project/ui/wdg_settings.py
Labels: bug

#179 Docs: update and restructure documentation to fit 2.4+ plugin versions - part 1
  .gitignore
  docs/development/setup.md
  docs/index.md
  docs/static/config_window_en.png
  docs/static/config_window_fr.png
  docs/static/demo_sample_basic_result_browser.png
  docs/static/demo_sample_basic_result_menu_bar.png
  docs/static/demo_sample_basic_result_menu_layer_add.png
  docs/static/demo_sample_basic_setup.png
  docs/usage/en/index.md
  docs/usage/en/try_it.md
  docs/usage/en/with_qdt.md
  docs/usage/fr/index.md
  docs/usage/fr/try_it.md
  docs/usage/fr/with_qdt.md
  tests/projects/aeag-tiny.qgz
  tests/projects/test-versions.qgz
Labels: Documentation

#180 fix(settings): avoid check of project validity when using plugin settings
  menu_from_project/toolbelt/preferences.py
Labels: bug

#182 fix(ui): restore window's icon and title
  menu_from_project/ui/dlg_settings.py
  menu_from_project/ui/wdg_settings.py
Labels: UI
